### ISSUE TITLE
確認 model 已經建立完成

### ISSUE THREAD

**Issue by johnroyer** [johnroyer/library#1]
我直接從 天瓏書局提供的資料來作為建立 model 的依據。

目前有：

- Author：作者
- Book：僅紙本書籍，不包含電子書
- BookCover：書籍封面
- Publisher：出版商
- Shelf：個人書櫃
- Translator：譯者
- User .... 
- Vendor：書商 (出版商可能是碁峰，但是委託天瓏書局販售)

----

請幫我想想，還有哪一些重要的東西我沒想到的。
感謝。

**Comment by passionFarmer64** [comment]
ISBN
出版地
出版年
第幾刷
譯者

**Comment by johnroyer** [comment]
我忘記是第幾刷了

這個大概什麼時候會用到？

---
Cheers
日落 (Zero)


passionFarmer64 <notifications@github.com> 於 2020年5月8日 週五 下午4:49寫道：

**Comment by passionFarmer64** [comment]
我有時會注意一下這個
看有沒有更新

你現在提的這個 issue 是我要建 model 進去了嗎?
attribute 我自已決定?
上面列的是欄位還是表格呀?

**Comment by johnroyer** [comment]
上面是 model list。看起來沒問題，我先 commit 了

issued closed
