### ISSUE TITLE
初版、再版的 ISBN 是否相同？

### ISSUE THREAD

**Issue by johnroyer** [johnroyer/library#3]
@passionFarmer64 方便幫我查一下嗎？

如果 ISBN 沒有換，我 schema 就要大改了 Orz

**Comment by johnroyer** [comment]
http://isbn.ncl.edu.tw/NEW_ISBNNet/main_ProcessMenuItems.php?PHPSESSID=10lqikj6drokq5a1gvtg80tij5&Ptarget=166&Pact=ViewContent&Pval=166&Pfld=Ffile

再版書的 ISBN 會是新的

**Comment by passionFarmer64** [comment]
正要來看  你就自已解決了 XD
